name: Update Gradle Wrapper

on: workflow_dispatch

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: yeikel/update-gradle-wrapper-action@0c6a8724c11d54d5cd1e6fd4612f227c252b4cc4
        with:
         labels: dependencies
         distributions-base-url: "https://mycustomhost.com/distributions"
