name: Update Gradle Wrapper

on: workflow_dispatch

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: yeikel/update-gradle-wrapper-action@e40dc7a3954689ea9fb0cad83736dde50547f709
        with:
         labels: dependencies
         distributions-base-url: "https://mycustomhost.com/distributions"
